---
kind: pipeline
name: rspec

steps:
  - name: Build docker image
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
  - name: Fetch all tags
    image: docker:git
    commands:
      - git fetch --tags
      # Need to checkout master, remember current branch
      - git branch --show-current > .current-branch
      - git checkout master
      - git checkout `cat .current-branch` # Going back
  - name: rspec
    image: ${DRONE_REPO}:latest
    commands:
      - echo "Running on agent $DRONE_MACHINE"
      - gem install bundler -v 1.17.2
      - bundle install
      - bundle exec rake

