---
kind: pipeline
name: rspec

steps:
  - name: Fetch all tags
    image: docker:git
    commands:
      - git fetch --tags
      # Need to checkout master, remember current branch
      - git branch --show-current > .current-branch
      - git checkout master
      - git checkout `cat .current-branch` # Going back
  - name: rspec
    image: ruby:2.6.2
    commands:
      - apt-get update -qq
      - apt-get install cmake zlib1g zlib1g-dev -y
      - echo "Running on agent $DRONE_MACHINE"
      - gem install bundler -v 1.17.2
      - bundle install
      - bundle exec rake

