---
kind: pipeline
name: rspec

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags
  - name: rspec
    image: ruby:2.6.2
    commands:
      - echo "Running on agent $DRONE_MACHINE"
      - gem install bundler -v 1.17.2
      - bundle install
      - bundle exec rake

