---
kind: pipeline
name: rspec

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags
      # Need to checkout master, remember current branch
      - CURRENT_BRANCH=git branch --show-current
      - git checkout master
      - git checkout $CURRENT_BRANCH # Going back
  - name: rspec
    image: ruby:2.6.2
    commands:
      - echo "Running on agent $DRONE_MACHINE"
      - gem install bundler -v 1.17.2
      - bundle install
      - bundle exec rake

